name: Snake Contribution

on:
  workflow_dispatch:

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - name: Set Date
        id: date
        run: echo "::set-output name=date::$(date -d '2023-07-12 00:00:00' +'%Y-%m-%dT%H:%M:%S')"

      - name: Clone Repository
        uses: actions/checkout@v2

      - name: Create Empty Commit
        run: git commit --allow-empty -m "Snake commit" --date="${{ steps.date.outputs.date }}"

      - name: Push Changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
